file = open("class-notes.txt", "w")
file.write("Maths: Learn equations today\n")
file.write("Coding: Variables and loops\n")
file.write("Science: Photosynthesis\n")
file.write("Coding: If statements\n")
file.write("English: Essay writing\n")
file.write("Coding: Functions and recursion\n")
file.write("History: World War II\n")
file.close()

n = int(input("How many characters to preview? "))
file = open("class-notes.txt", "r")
print(file.read(n))
file.close()
